import "./global.css";

export const metadata = {
  title: "Next.js",

  description: "Generated by Next.js"
};

import { Urbanist } from "next/font/google";

const urbanist = Urbanist({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin-ext"],
  display: "swap"
});

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <head></head>
      <body className={urbanist.className}>{children}</body>
    </html>
  );
}
